import speech_recognition as sr
from nltk.corpus import cmudict
import pyttsx3
import Levenshtein
import numpy as np
import wikipedia
import webbrowser

# Initialize pyttsx3 engine
engine = pyttsx3.init('sapi5')
voices = engine.getProperty('voices')
engine.setProperty('voice', voices[0].id)

# Function to make the AI assistant speak
def speak(audio):
    engine.say(audio)
    engine.runAndWait()

# Function to calculate Levenshtein distance (edit distance)
def levenshtein_distance(word1, word2):
    return Levenshtein.distance(word1, word2)

# Function to suggest corrections based on phonetic transcriptions
def correct_word(user_word, correct_words_phonetic):
    min_distance = float('inf')
    suggested_correction = None

    for correct_word, correct_word_phonetic in correct_words_phonetic.items():
        for phonetic_transcription in correct_word_phonetic:
            distance = levenshtein_distance(user_word, phonetic_transcription)
            if distance < min_distance:
                min_distance = distance
                suggested_correction = correct_word

    return suggested_correction

# Function to take command from the user using speech recognition
def takeCommand():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening...")
        r.pause_threshold = 1
        audio = r.listen(source)

    try:
        print("Recognizing...")
        query = r.recognize_google(audio, language='en-in')
        print(f"User said: {query}\n")
    except Exception as e:
        print("Say that again please...")
        return "None"
    return query


# Sample correct words and their phonetic transcriptions
correct_words_phonetic = {
    'this': ['DH IH S'],
    'that': ['DH AE T'],
    'is': ['IH Z'],
    'are': ['AA R'],
    'am': ['AE M'],
    'an': ['AE N'],
    'and': ['AE N D'],
    'the': ['DH AH'],
    'it': ['IH T'],
    'of': ['AH V'],
    'to': ['T UW'],
    'in': ['IH N'],
    'on': ['AA N'],
    'at': ['AE T'],
    'as': ['AE Z'],
    'by': ['B AY'],
    'for': ['F AO R'],
    'with': ['W IH DH'],
    'or': ['AO R'],
    'but': ['B AH T'],
    'not': ['N AA T'],
    'from': ['F R AH M'],
    'you': ['Y UW'],
    'we': ['W IY'],
    'he': ['HH IY'],
    'she': ['SH IY'],
    'they': ['DH EY'],
    'I': ['AY'],
    'me': ['M IY'],
    'my': ['M AY'],
    'your': ['Y AO R'],
    'our': ['AW ER'],
    'his': ['HH IH Z'],
    'her': ['HH ER'],
    'its': ['IH T S'],
    'their': ['DH EH R'],
    'us': ['AH S'],
    'all': ['AO L'],
    'any': ['EH N IY'],
    'some': ['S AH M'],
    'no': ['N OW'],
    'yes': ['Y EH S'],
    'now': ['N AW'],
    'then': ['DH EH N'],
    'here': ['HH IH R'],
    'there': ['DH EH R'],
    'where': ['W EH R'],
    'when': ['W EH N'],
    'how': ['HH AW'],
    'why': ['W AY'],
    'which': ['W IH CH'],
    'what': ['W AH T'],
    'who': ['HH UW'],
    'whom': ['HH UW M'],
    'whose': ['HH UW Z'],
    'each': ['IY CH'],
    'both': ['B OW TH'],
    'few': ['F Y UW'],
    'many': ['M EH N IY'],
    'more': ['M AO R'],
    'most': ['M OW S T'],
    'other': ['AH DH ER'],
    'somebody': ['S AH M B AH D IY'],
    'someone': ['S AH M W AH N'],
    'something': ['S AH M TH IH NG'],
    'every': ['EH V R IY'],
    'everyone': ['EH V R IY W AH N'],
    'everybody': ['EH V R IY B AA D IY'],
    'everything': ['EH V R IY TH IH NG'],
    'anything': ['EH N IY TH IH NG'],
    'nothing': ['N AH TH IH NG'],
    'nowhere': ['N OW W EH R'],
    'anywhere': ['EH N IY W EH R'],
    'somewhere': ['S AH M W EH R'],
    'everywhere': ['EH V R IY W EH R'],
    'wherever': ['W EH R EH V ER'],
    'whatever': ['W AH T EH V ER'],
    'whenever': ['W EH N EH V ER'],
    'however': ['HH AW EH V ER'],
    'whyever': ['W AY EH V ER'],
    'hence': ['HH EH N S'],
    'hither': ['HH IH DH ER'],
    'thither': ['DH IH DH ER'],
    'whence': ['W EH N S'],
    'whither': ['W IH DH ER'],
    'thenceforth': ['DH EH N S F AO R TH'],
    'hereafter': ['HH IH R AE F T ER'],
    'thereafter': ['DH EH R AE F T ER'],
    'whereafter': ['W EH R AE F T ER'],
    'whereupon': ['W EH R AH P AA N'],
    'hereby': ['HH IH R B AY'],
    'thereby': ['DH EH R B AY'],
    'whereby': ['W EH R B AY'],
    'wherein': ['W EH R IH N'],
    'therein': ['DH EH R IH N'],
    'whereupon': ['W EH R AH P AA N'],
    'herewith': ['HH EH R W IH DH'],
    'forthwith': ['F AO R TH W IH DH'],
    'otherwise': ['AH DH ER W AY Z'],
    'herein': ['HH IH R IH N'],
    'hereto': ['HH IH R IH T UW'],
    'hereof': ['HH IH R AH V'],
    'thereof': ['DH EH R AH V'],
    'whereof': ['W EH R AH V'],
    'hereon': ['HH IH R AA N'],
    'thereon': ['DH EH R AA N'],
    'whereon': ['W EH R AA N'],
    'hereby': ['HH IH R B AY'],
    'thereby': ['DH EH R B AY'],
    'whereby': ['W EH R B AY'],
    'hereunder': ['HH IH R AH N D ER'],
    'thereunder': ['DH EH R AH N D ER'],
    'whereunder': ['W EH R AH N D ER'],
    'hereunto': ['HH IH R AH N T UW'],
    'thereunto': ['DH EH R AH N T UW'],
    'whereunto': ['W EH R AH N T UW'],
    'abandon': ['AH B AE N D AH N'],
    'ability': ['AH B IH L IH T IY'],
    'absence': ['AE B S AH N S'],
    'academy': ['AH K AE D AH M IY'],
    'account': ['AH K AW N T'],
    'accurate': ['AE K Y ER AH T'],
    'achieve': ['AH CH IY V'],
    'acknowledge': ['AE K N AA L IH JH'],
    'activate': ['AE K T AH V EY T'],
    'admire': ['AH D M AY ER'],
    'adventure': ['AE D V EH N CH ER'],
    'advocate': ['AE D V AH K AH T'],
    'affection': ['AH F EH K SH AH N'],
    'against': ['AH G EH N S T'],
    'airplane': ['EH R P L EY N'],
    'alcohol': ['AE L K AH HH AO L'],
    'allege': ['AH L EH JH'],
    'ambition': ['AE M B IH SH AH N'],
    'analyze': ['AE N AH L AY Z'],
    'ancient': ['EY N CH AH N T'],
    'announce': ['AH N AW N S'],
    'anxiety': ['AE NG Z AY AH T IY'],
    'apology': ['AH P AA L AH JH IY'],
    'appetite': ['AE P AH T AY T'],
    'approach': ['AH P R OW CH'],
    'arrogant': ['EH R AH G AH N T'],
    'assembly': ['AH S EH M B L IY'],
    'athlete': ['AE TH L IY T'],
    'atmosphere': ['AE T M AH S F IH R'],
    'attribute': ['AH T R AH B Y UW T'],
    'audience': ['AO D IY AH N S'],
    'authorize': ['AO TH ER AY Z'],
    'automatic': ['AO T AH M AE T IH K'],
    'avocado': ['AE V AH K AA D OW'],
    'awesome': ['AO S AH M'],
    'balance': ['B AE L AH N S'],
    'beautiful': ['B Y UW T AH F AH L'],
    'believe': ['B IH L IY V'],
    'benefit': ['B EH N AH F AH T'],
    'boundary': ['B AW N D ER IY'],
    'bravery': ['B R EY V ER IY'],
    'broadcast': ['B R AO D K AE S T'],
    'calendar': ['K AE L AH N D ER'],
    'campaign': ['K AE M P EY N'],
    'capacity': ['K AH P AE S AH T IY'],
    'captain': ['K AE P T AH N'],
    'category': ['K AE T AH G AO R IY'],
    'celebrate': ['S EH L AH B R EY T'],
    'ceremony': ['S EH R AH M AH N IY'],
    'challenge': ['CH AE L AH N JH'],
    'champion': ['CH AE M P IY AH N'],
    'character': ['K EH R IH K T ER'],
    'charity': ['CH EH R AH T IY'],
    'chemical': ['K EH M IH K AH L'],
    'childhood': ['CH AY L D HH UH D'],
    'choice': ['CH OY S'],
    'chocolate': ['CH AA K L AH T'],
    'chorus': ['K AO R AH S'],
    'circumstance': ['S ER K AH M S T AE N S'],
    'citizen': ['S IH T AH Z AH N'],
    'civilize': ['S IH V AH L AY Z'],
    'classic': ['K L AE S IH K'],
    'clarity': ['K L EH R AH T IY'],
    'climate': ['K L AY M AH T'],
    'clothes': ['K L OW DH Z'],
    'cluster': ['K L AH S T ER'],
    'coconut': ['K OW K AH N AH T'],
    'collect': ['K AH L EH K T'],
    'comfort': ['K AH M F ER T'],
    'commerce': ['K AA M ER S'],
    'community': ['K AH M Y UW N AH T IY'],
    'compassion': ['K AH M P AE SH AH N'],
    'compatible': ['K AH M P AE T AH B AH L'],
    'compete': ['K AH M P IY T'],
    'complain': ['K AH M P L EY N'],
    'complete': ['K AH M P L IY T'],
    'compose': ['K AH M P OW Z'],
    'concentrate': ['K AH N S AH N T R EY T'],
    'conclude': ['K AH N K L UW D'],
    'confident': ['K AA N F AH D AH N T'],
    'conflict': ['K AH N F L IH K T'],
    'congress': ['K AA NG G R EH S'],
    'conquer': ['K AA NG K ER'],
    'conscious': ['K AA N SH AH S'],
    'consider': ['K AH N S IH D ER'],
    'consistent': ['K AH N S IH S T AH N T'],
    'constantly': ['K AA N S T AH N T L IY'],
    'contribute': ['K AH N T R AH B Y UW T'],
    'convince': ['K AH N V IH N S'],
    'corridor': ['K AO R AH D ER'],
    'courage': ['K ER AH JH'],
    'creation': ['K R IY EY SH AH N'],
    'creative': ['K R IY EY T IH V'],
    'crisis': ['K R AY S AH S'],
    'criticize': ['K R IH T AH S AY Z'],
    'crucial': ['K R UW SH AH L'],
    'culture': ['K AH L CH ER'],
    'curious': ['K Y UH R IY AH S'],
    'customer': ['K AH S T AH M ER'],
    'danger': ['D EY N JH ER'],
    'darkness': ['D AA R K N AH S'],
    'daughter': ['D AO T ER'],
    'deadline': ['D EH D L AY N'],
    'decision': ['D IH S IH ZH AH N'],
    'declare': ['D IH K L EH R'],
    'defend': ['D IH F EH N D'],
    'deficit': ['D EH F AH S AH T'],
    'delicate': ['D EH L AH K AH T'],
    'deliver': ['D IH L IH V ER'],
    'demand': ['D IH M AE N D'],
    'demonstrate': ['D EH M AH N S T R EY T'],
    'denounce': ['D IH N AW N S'],
    'depart': ['D IH P AA R T'],
    'dependent': ['D IH P EH N D AH N T'],
    'describe': ['D IH S K R AY B'],
    'deserve': ['D IH Z ER V'],
    'design': ['D IH Z AY N'],
    'determine': ['D IH T ER M AH N'],
    'development': ['D IH V EH L AH P M AH N T'],
    'devote': ['D IH V OW T'],
    'diagnosis': ['D AY AH G N OW S IH S'],
    'dialogue': ['D AY AH L AO G'],
    'diamond': ['D AY AH M AH N D'],
    'dictate': ['D IH K T EY T'],
    'different': ['D IH F ER AH N T'],
    'dilemma': ['D IH L EH M AH'],
    'dimension': ['D IH M EH N SH AH N'],
    'dinner': ['D IH N ER'],
    'diplomat': ['D IH P L AH M AE T'],
    'disagree': ['D IH S AH G R IY'],
    'disappear': ['D IH S AH P IH R'],
    'disaster': ['D IH Z AE S T ER'],
    'discipline': ['D IH S AH P L AH N'],
    'disconnect': ['D IH S K AH N EH K T'],
    'discovery': ['D IH S K AH V ER IY'],
    'discuss': ['D IH S K AH S'],
    'disease': ['D IH Z IY Z'],
    'dismiss': ['D IH S M IH S'],
    'distance': ['D IH S T AH N S'],
    'distinct': ['D IH S T IH NG K T'],
    'diverse': ['D AY V ER S'],
    'dividend': ['D IH V AH D EH N D'],
    'domestic': ['D AH M EH S T IH K'],
    'dominant': ['D AA M AH N AH N T'],
    'dramatic': ['D R AH M AE T IH K'],
    'duration': ['D Y UH R EY SH AH N'],
    'dynamics': ['D AY N AE M IH K S'],
    'earthquake': ['ER TH K W EY K'],
    'ecosystem': ['IH K OW S IH S T AH M'],
    'education': ['EH JH AH K EY SH AH N'],
    'effective': ['IH F EH K T IH V'],
    'effort': ['EH F ER T'],
    'elaborate': ['IH L AE B ER AH T'],
    'election': ['IH L EH K SH AH N'],
    'eliminate': ['IH L IH M AH N EY T'],
    'embarrass': ['IH M B EH R AH S'],
    'emergency': ['IH M ER JH AH N S IY'],
    'emphasize': ['EH M F AH S AY Z'],
    'employee': ['EH M P L OY IY'],
    'enormous': ['IH N AO R M AH S'],
    'enterprise': ['EH N T ER P R AY Z'],
    'entertain': ['EH N T ER T EY N'],
    'enthusiasm': ['EH N TH Y UW Z IY AE Z AH M'],
    'environment': ['IH N V AY R AH N M AH N T'],
    'episode': ['EH P IH S OW D'],
    'equality': ['IH K W AA L AH T IY'],
    'equation': ['IH K W EY ZH AH N'],
    'equipment': ['IH K W IH P M AH N T'],
    'error': ['EH R ER'],
    'essential': ['IH S EH N SH AH L'],
    'establish': ['IH S T AE B L IH SH'],
    'estimate': ['EH S T AH M AH T'],
    'evaluate': ['IH V AE L Y UW EY T'],
    'eventually': ['IH V EH N CH UW AH L IY'],
    'evidence': ['EH V AH D AH N S'],
    'evolve': ['IH V AA L V'],
    'exaggerate': ['IH G Z AE DZH ER EY T'],
    'examine': ['IH G Z AE M IH N'],
    'example': ['IH G Z AE M P AH L'],
    'exceed': ['IH K S IY D'],
    'exception': ['IH K S EH P SH AH N'],
    'excessive': ['IH K S EH S IH V'],
    'exchange': ['IH K S CH EY N JH'],
    'excitement': ['IH K S AY T M AH N T'],
    'exclusive': ['IH K S K L UW S IH V'],
    'executive': ['IH G Z EH K Y UW T IH V'],
    'exercise': ['EH K S ER S AY Z'],
    'exhibit': ['IH G Z IH B IH T'],
    'existence': ['IH G Z IH S T AH N S'],
    'expand': ['IH K S P AE N D'],
    'expansion': ['IH K S P AE N SH AH N'],
    'expectation': ['EH K S P EH K T EY SH AH N'],
    'expedition': ['EH K S P AH D IH SH AH N'],
    'experience': ['IH K S P IH R IY AH N S'],
    'experiment': ['IH K S P EH R AH M AH N T'],
    'expertise': ['EH K S P ER T IY Z'],
    'explain': ['IH K S P L EY N'],
    'explore': ['IH K S P L AO R'],
    'expression': ['IH K S P R EH SH AH N'],
    'extension': ['IH K S T EH N SH AH N'],
    'extensive': ['IH K S T EH N S IH V'],
    'external': ['IH K S T ER N AH L'],
    'extraordinary': ['IH K S T R AO R D AH N EH R IY'],
    'extraction': ['IH K S T R AE K SH AH N'],
    'facade': ['F AH S AA D'],
    'facility': ['F AH S IH L AH T IY'],
    'factor': ['F AE K T ER'],
    'faculty': ['F AE K AH L T IY'],
    'failure': ['F EY L Y ER'],
    'familiar': ['F AH M IH L Y ER'],
    'fantasy': ['F AE N T AH S IY'],
    'fascinate': ['F AE S AH N EY T'],
    'favorite': ['F EY V ER IH T'],
    'federal': ['F EH D ER AH L'],
    'fertility': ['F ER T IH L AH T IY'],
    'fiction': ['F IH K SH AH N'],
    'fidelity': ['F AH D EH L AH T IY'],
    'finance': ['F AH N AE N S'],
    'fingerprint': ['F IH NG G ER P R IH N T'],
    'flexible': ['F L EH K S AH B AH L'],
    'focus': ['F OW K AH S'],
    'foliage': ['F OW L IY AH JH'],
    'forensic': ['F ER EH N S IH K'],
    'forgive': ['F ER G IH V'],
    'formation': ['F AO R M EY SH AH N'],
    'fortunate': ['F AO R CH AH N AH T'],
    'foundation': ['F AW N D EY SH AH N'],
    'fraction': ['F R AE K SH AH N'],
    'fragile': ['F R AE JH AH L'],
    'framework': ['F R EY M W ER K'],
    'frequent': ['F R IY K W AH N T'],
    'friction': ['F R IH K SH AH N'],
    'frontier': ['F R AH N T IH R'],
    'fulfill': ['F UH L F IH L'],
    'fundamental': ['F AH N D AH M EH N T AH L'],
    'gallery': ['G AE L ER IY'],
    'garbage': ['G AA R B IH JH'],
    'generate': ['JH EH N ER EY T'],
    'generation': ['JH EH N ER EY SH AH N'],
    'genetic': ['JH AH N EH T IH K'],
    'gentleman': ['JH EH N AH L M AH N'],
    'genuine': ['JH EH N Y UW AH N'],
    'geography': ['JH IY AA G R AH F IY'],
    'gesture': ['JH EH S CH ER'],
    'gigantic': ['JH AY G AE N T IH K'],
    'glance': ['G L AE N S'],
    'government': ['G AH V ER N M AH N T'],
    'graduate': ['G R AE JH UW EY T'],
    'grateful': ['G R EY T F AH L'],
    'gregarious': ['G R EH G EH R IY AH S'],
    'grief': ['G R IY F'],
    'guarantee': ['G EH R AH N T IY'],
    'guidance': ['G AY D AH N S'],
    'habitat': ['HH AE B AH T AE T'],
    'harass': ['HH AH R AE S'],
    'hazard': ['HH AE Z ER D'],
    'headache': ['HH EH D EY K'],
    'healthy': ['HH EH L TH IY'],
    'heaven': ['HH EH V AH N'],
    'hectic': ['HH EH K T IH K'],
    'height': ['HH AY T'],
    'heritage': ['HH EH R IH T AH JH'],
    'hierarchy': ['HH AY ER AE R K IY'],
    'highlight': ['HH AY L AY T'],
    'hindrance': ['HH IH N D R AH N S'],
    'historical': ['HH IH S T AO R IH K AH L'],
    'hobby': ['HH AA B IY'],
    'holiday': ['HH AA L AH D EY'],
    'homogeneous': ['HH OW M AH JH IY N IY AH S'],
    'honesty': ['AA N AH S T IY'],
    'horizon': ['HH ER AY Z AH N'],
    'hostile': ['HH AA S T AH L'],
    'household': ['HH AW S HH OW L D'],
    'humility': ['HH Y UW M IH L AH T IY'],
    'hurricane': ['HH ER AH K EY N'],
    'hypothesis': ['HH AY P AA TH AH S AH S'],
    'iconic': ['AY K AA N IH K'],
    'idealize': ['AY D IY AH L AY Z'],
    'identical': ['AY D EH N T IH K AH L'],
    'identify': ['AY D EH N T AH F AY'],
    'identity': ['AY D EH N T AH T IY'],
    'ignorance': ['IH G N ER AH N S'],
    'illegal': ['IH L IY G AH L'],
    'illuminate': ['IH L UW M AH N EY T'],
    'illusion': ['IH L UW ZH AH N'],
    'imagination': ['IH M AE JH AH N EY SH AH N'],
    'immediate': ['IH M IY D IY AH T'],
    'immense': ['IH M EH N S'],
    'immigrant': ['IH M IH G R AH N T'],
    'impact': ['IH M P AE K T'],
    'imperial': ['IH M P IY R IY AH L'],
    'implement': ['IH M P L AH M EH N T'],
    'implicit': ['IH M PL IH S AH T'],
    'importance': ['IH M P AO R T AH N S'],
    'impose': ['IH M P OW Z'],
    'impression': ['IH M P R EH SH AH N'],
    'improve': ['IH M P R UW V'],
    'incidence': ['IH N S AH D AH N S'],
    'inclusion': ['IH N K L UW ZH AH N'],
    'income': ['IH N K AH M'],
    'incorporate': ['IH N K AO R P ER EY T'],
    'incredible': ['IH N K R EH D AH B AH L'],
    'independence': ['IH N D AH P EH N D AH N S'],
    'index': ['IH N D EH K S'],
    'indicate': ['IH N D AH K EY T'],
    'individual': ['IH N D AH V IH JH OO AH L'],
    'industry': ['IH N D AH S T R IY'],
    'inequality': ['IH N IH K W AA L AH T IY'],
    'infectious': ['IH N F EH K SH AH S'],
    'inferior': ['IH N F IY R IY ER'],
    'inflation': ['IH N F L EY SH AH N'],
    'influence': ['IH N F L UW AH N S'],
    'inform': ['IH N F AO R M'],
    'infrastructure': ['IH N F R AH S T R AH K CH ER'],
    'ingredient': ['IH N G R IY JH AH N T'],
    'inhabit': ['IH N H AE B AH T'],
    'initial': ['IH N IH SH AH L'],
    'initiate': ['IH N IH SH IY EY T'],
    'innovate': ['IH N AH V EY T'],
    'inquiry': ['IH N K W AY R IY'],
    'insect': ['IH N S EH K T'],
    'insert': ['IH N S ER T'],
    'insight': ['IH N S AY T'],
    'insist': ['IH N S IH S T'],
    'inspection': ['IH N S P EH K SH AH N'],
    'inspire': ['IH N S P AY ER'],
    'install': ['IH N S T AO L'],
    'instance': ['IH N S T AH N S'],
    'instinct': ['IH N S T IH NG K T'],
    'institute': ['IH N S T AH T UW T'],
    'institution': ['IH N S T AH T UW SH AH N'],
    'instruction': ['IH N S T R AH K SH AH N'],
    'insufficient': ['IH N S AH F IH SH AH N T'],
    'integrate': ['IH N T AH G R EY T'],
    'integrity': ['IH N T EH G R AH T IY'],
    'intelligence': ['IH N T EH L AH JH AH N S'],
    'intense': ['IH N T EH N S'],
    'intent': ['IH N T EH N T'],
    'interaction': ['IH N T ER AE K SH AH N'],
    'interact': ['IH N T ER AE K T'],
    'interfere': ['IH N T ER F IH R'],
    'interior': ['IH N T IH R IY ER'],
    'intermediate': ['IH N T ER M IY D IY AH T'],
    'internal': ['IH N T ER N AH L'],
    'interpret': ['IH N T ER P R AH T'],
    'intervene': ['IH N T ER V IY N'],
    'intimate': ['IH N T AH M AH T'],
    'intrigue': ['IH N T R IY G'],
    'introduce': ['IH N T R AH D UW S'],
    'investigate': ['IH N V EH S T AH G EY T'],
    'involve': ['IH N V AA L V'],
    'irrigate': ['IH R AH G EY T'],
    'isolate': ['AY S AH L EY T'],
    'jealousy': ['JH EH L AH S IY'],
    'judgment': ['JH AH JH M AH N T'],
    'junior': ['JH UW N Y ER'],
    'justice': ['JH AH S T AH S'],
    'keyboard': ['K IY B AO R D'],
    'knowledge': ['N AA L AH JH'],
    'laboratory': ['L AE B ER AH T AO R IY'],
    'landscape': ['L AE N D S K EY P'],
    'language': ['L AE NG G W AH JH'],
    'laundry': ['L AO N D R IY'],
    'laughter': ['L AE F T ER'],
    'latitude': ['L AE T AH T UW D'],
    'lawyer': ['L AO Y ER'],
    'leadership': ['L IY D ER SH IH P'],
    'legitimate': ['L AH JH IH T AH M AH T'],
    'leisure': ['L EH ZH ER'],
    'length': ['L EH NG K TH'],
    'liberty': ['L IH B ER T IY'],
    'lightning': ['L AY T N IH NG'],
    'limb': ['L IH M'],
    'limitation': ['L IH M AH T EY SH AH N'],
    'linguistic': ['L IH NG G W IH S T IH K'],
    'literature': ['L IH T ER AH CH ER'],
    'lonely': ['L OW N L IY'],
    'longitude': ['L AA N JH AH T UW D'],
    'loose': ['L UW S'],
    'lounge': ['L AW N JH'],
    'loyalty': ['L OY AH L T IY'],
    'magnitude': ['M AE GN AH T UW D'],
    'maintain': ['M EY N T EY N'],
    'majestic': ['M AH JH EH S T IH K'],
    'majority': ['M AH JH AO R IH T IY'],
    'manipulate': ['M AH N IH P Y AH L EY T'],
    'manner': ['M AE N ER'],
    'manufacture': ['M AE N Y AH F AE K CH ER'],
    'marketing': ['M AA R K AH T IH NG'],
    'marriage': ['M EH R IH JH'],
    'massive': ['M AE S IH V'],
    'masterpiece': ['M AE S T ER P IY S'],
    'material': ['M AH T IH R IY AH L'],
    'maximum': ['M AE K S AH M AH M'],
    'mechanism': ['M AH K AH N IH Z AH M'],
    'medieval': ['M IY D IY V AH L'],
    'meditate': ['M EH D AH T EY T'],
    'melody': ['M EH L AH D IY'],
    'memorable': ['M EH M ER AH B AH L'],
    'mental': ['M EH N T AH L'],
    'mercy': ['M ER S IY'],
    'merit': ['M EH R IH T'],
    'metabolism': ['M EH T AH B AH L IH Z AH M'],
    'metallic': ['M EH T AE L IH K'],
    'methodology': ['M EH TH AH D AA L AH JH IY'],
    'microphone': ['M AY K R AH F OW N'],
    'midnight': ['M IH D N AY T'],
    'migration': ['M AY G R EY SH AH N'],
    'milestone': ['M AY L S T OW N'],
    'military': ['M IH L AH T EH R IY'],
    'minimal': ['M IH N AH M AH L'],
    'minimize': ['M IH N AH M AY Z'],
    'ministry': ['M IH N IH S T R IY'],
    'minority': ['M AY N AO R AH T IY'],
    'miracle': ['M IH R AH K AH L'],
    'miserable': ['M IH Z ER AH B AH L'],
    'mission': ['M IH SH AH N'],
    'mixture': ['M IH K S CH ER'],
    'mobile': ['M OW B AH L'],
    'moderate': ['M AA D ER AH T'],
    'modern': ['M AA D ER N'],
    'momentum': ['M OW M EH N T AH M'],
    'monitor': ['M AA N AH T ER'],
    'monument': ['M AA N Y UW M AH N T'],
    'morality': ['M AH R AE L AH T IY'],
    'mosquito': ['M AH S K IH T OW'],
    'motivate': ['M OW T AH V EY T'],
    'motive': ['M OW T IH V'],
    'multimedia': ['M AH L T IY M IY D IY AH'],
    'municipal': ['M Y UW N IH S AH P AH L'],
    'museum': ['M Y UW Z IY AH M'],
    'mutation': ['M Y UW T EY SH AH N'],
    'mysterious': ['M IH S T IY R IY AH S'],
    'mythology': ['M IH TH AA L AH JH IY'],
    'narrative': ['N EH R AH T IH V'],
    'navigate': ['N AE V AH G EY T'],
    'negotiate': ['N IH G OW SH IY EY T'],
    'neighbour': ['N EY B ER'],
    'nervous': ['N ER V AH S'],
    'network': ['N EH T W ER K'],
    'neutral': ['N UW T R AH L'],
    'nominate': ['N AA M AH N EY T'],
    'normal': ['N AO R M AH L'],
    'notion': ['N OW SH AH N'],
    'nuclear': ['N UW K L IY ER'],
    'numerous': ['N UW M AH R AH S'],
    'nutrition': ['N UW T R IH SH AH N'],
    'obstacle': ['AA B S T AH K AH L'],
    'obtain': ['AH B T EY N'],
    'occasion': ['AH K EY ZH AH N'],
    'occurrence': ['AH K ER AH N S'],
    'offense': ['AH F EH N S'],
    'official': ['AH F IH SH AH L'],
    'omission': ['AH M IH SH AH N'],
    'opponent': ['AH P AH N AH N T'],
    'oppose': ['AH P OW Z'],
    'optimistic': ['AA P T IH M IH S T IH K'],
    'orchestra': ['AO R K AH S T R AH'],
    'organize': ['AO R G AH N AY Z'],
    'orientation': ['AO R IY AH N T EY SH AH N'],
    'original': ['ER IH JH AH N AH L'],
    'outrage': ['AW T R EY JH'],
    'overcome': ['OW V ER K AH M'],
    'overlook': ['OW V ER L UH K'],
    'overwhelm': ['OW V ER W EH L M'],
    'ownership': ['OW N ER SH IH P'],
    'painful': ['P EY N F AH L'],
    'palace': ['P AE L AH S'],
    'pamphlet': ['P AE M FL AH T'],
    'panic': ['P AE N IH K'],
    'parade': ['P ER EY D'],
    'parallel': ['P AE R AH L EH L'],
    'parameter': ['P ER AE M AH T ER'],
    'participate': ['P AA R T IH S IH P EY T'],
    'partnership': ['P AA R T N ER SH IH P'],
    'passage': ['P AE S IH JH'],
    'passion': ['P AE SH AH N'],
    'patience': ['P EY SH AH N S'],
    'patrol': ['P AH T R OW L'],
    'pattern': ['P AE T ER N'],
    'payment': ['P EY M AH N T'],
    'peculiar': ['P AH K Y UW L Y ER'],
    'pedestrian': ['P EH D AH S T R IY AH N'],
    'penalty': ['P EH N AH L T IY'],
    'perceive': ['P ER S IY V'],
    'perception': ['P ER S EH P SH AH N'],
    'perfect': ['P ER F EH K T'],
    'performance': ['P ER F AO R M AH N S'],
    'permanent': ['P ER M AH N AH N T'],
    'permission': ['P ER M IH SH AH N'],
    'persist': ['P ER S IH S T'],
    'personnel': ['P ER S AH N EH L'],
    'perspective': ['P ER S P EH K T IH V'],
    'persuade': ['P ER S W EY D'],
    'pesticide': ['P EH S T AH S AY D'],
    'petroleum': ['P EH T R OW L IY AH M'],
    'phenomenon': ['F IH N AA M AH N AH N'],
    'philosophy': ['F IH L AA S AH F IY'],
    'photograph': ['F OW T AH G R AE F'],
    'physical': ['F IH Z IH K AH L'],
    'pioneer': ['P AY AH N IH R'],
    'pipeline': ['P AY P L AY N'],
    'pistol': ['P IH S T AH L'],
    'plausible': ['P L AW Z AH B AH L'],
    'pleasure': ['P L EH ZH ER'],
    'plentiful': ['P L EH N T IH F AH L'],
    'poetry': ['P OW AH T R IY'],
    'policy': ['P AA L AH S IY'],
    'political': ['P AH L IH T IH K AH L'],
    'pollution': ['P AH L UW SH AH N'],
    'popularity': ['P AA P Y AH L EH R IH T IY'],
    'portfolio': ['P AO R T F OW L IY OW'],
    'portion': ['P AO R SH AH N'],
    'portrait': ['P AO R T R AH T'],
    'position': ['P AH Z IH SH AH N'],
    'positive': ['P AA Z AH T IH V'],
    'possess': ['P AH Z EH S'],
    'posture': ['P AA S CH ER'],
    'potential': ['P AH T EH N SH AH L'],
    'practical': ['P R AE K T IH K AH L'],
    'precaution': ['P R IH K AO SH AH N'],
    'precede': ['P R IH S IY D'],
    'precise': ['P R IH S AY S'],
    'predict': ['P R IH D IH K T'],
    'prejudice': ['P R EH JH AH D AH S'],
    'premise': ['P R EH M IH S'],
    'preoccupy': ['P R IY AH K Y UW P AY'],
    'prescribe': ['P R AH S K R AY B'],
    'presence': ['P R EH Z AH N S'],
    'preserve': ['P R IH Z ER V'],
    'press': ['P R EH S'],
    'prevalent': ['P R EH V AH L AH N T'],
    'primary': ['P R AY M EH R IY'],
    'priority': ['P R AY AO R AH T IY'],
    'privilege': ['P R IH V AH L AH JH'],
    'probability': ['P R AA B AH B IH L AH T IY'],
    'problem': ['P R AA B L AH M'],
    'procedure': ['P R AH S IY JH ER'],
    'proceed': ['P R AH S IY D'],
    'process': ['P R AA S EH S'],
    'profession': ['P R AH F EH SH AH N'],
    'professor': ['P R AH F EH S ER'],
    'proficient': ['P R AH F IH SH AH N T'],
    'profile': ['P R OW F AY L'],
    'profit': ['P R AA F IH T'],
    'profound': ['P R OW F AW N D'],
    'progress': ['P R AH G R EH S'],
    'prohibit': ['P R AH HH IH B AH T'],
    'project': ['P R AA JH EH K T'],
    'prolong': ['P R OW L AO NG'],
    'prominent': ['P R AA M AH N AH N T'],
    'promise': ['P R AA M IH S'],
    'prompt': ['P R AA M P T'],
    'pronounce': ['P R AH N AW N S'],
    'propaganda': ['P R AA P AH G AE N D AH'],
    'property': ['P R AA P ER T IY'],
    'proportion': ['P R AH P AO R SH AH N'],
    'proposal': ['P R AH P OW Z AH L'],
    'prosperity': ['P R AA S P EH R AH T IY'],
    'protect': ['P R AH T EH K T'],
    'protest': ['P R AH T EH S T'],
    'protocol': ['P R OW T AH K AO L'],
    'proud': ['P R AW D'],
    'provide': ['P R AH V AY D'],
    'psychology': ['S AY K AA L AH JH IY'],
    'public': ['P AH B L IH K'],
    'publication': ['P AH B L IH K EY SH AH N'],
    'pulmonary': ['P UH L M AH N EH R IY'],
    'punctual': ['P AH NG K CH UW AH L'],
    'puzzle': ['P AH Z AH L'],
    'qualification': ['K W AA L AH F AH K EY SH AH N'],
    'qualify': ['K W AA L AH F AY'],
    'quantity': ['K W AA N T AH T IY'],
    'quarrel': ['K W AO R AH L'],
    'quarter': ['K W AO R T ER'],
    'question': ['K W EH S CH AH N'],
    'quiet': ['K W AY AH T'],
    'radical': ['R AE D IH K AH L'],
    'railroad': ['R EY L R OW D'],
    'random': ['R AE N D AH M'],
    'rapid': ['R AE P IH D'],
    'ratify': ['R AE T IH F AY'],
    'rational': ['R AE SH AH N AH L'],
    'react': ['R IY AE K T'],
    'readily': ['R EH D AH L IY'],
    'realistic': ['R IY AH L IH S T IH K'],
    'realize': ['R IY AH L AY Z'],
    'reason': ['R IY Z AH N'],
    'reasonable': ['R IY Z AH N AH B AH L'],
    'rebel': ['R EH B AH L'],
    'recall': ['R IY K AO L'],
    'recession': ['R IH S EH SH AH N'],
    'recipe': ['R EH S AH P IY'],
    'recipient': ['R IH S AH P IY AH N T'],
    'reckless': ['R EH K L AH S'],
    'recognition': ['R EH K AH G N IH SH AH N'],
    'recommend': ['R EH K AH M EH N D'],
    'reconcile': ['R EH K AH N S AY L'],
    'recover': ['R IH K AH V ER'],
    'recreation': ['R EH K R IY EY SH AH N'],
    'recruit': ['R IH K R UW T'],
    'refugee': ['R EH F Y UW JH IY'],
    'refrain': ['R IY F R EY N'],
    'refresh': ['R IY F R EH SH'],
    'refuge': ['R EH F Y UW JH'],
    'register': ['R EH JH AH S T ER'],
    'regret': ['R IH G R EH T'],
    'regular': ['R EH G Y AH L ER'],
    'regulate': ['R EH G Y AH L EY T'],
    'reinforce': ['R IY AH N F AO R S'],
    'reiterate': ['R IY IH T ER EY T'],
    'rejection': ['R IH JH EH K SH AH N'],
    'relax': ['R IY L AE K S'],
    'release': ['R IY L IY S'],
    'relevant': ['R EH L AH V AH N T'],
    'reliable': ['R IY L AY AH B AH L'],
    'reluctant': ['R IH L AH K T AH N T'],
    'remark': ['R IH M AA R K'],
    'remedy': ['R EH M AH D IY'],
    'reminder': ['R IY M AY N D ER'],
    'remote': ['R IH M OW T'],
    'renovate': ['R EH N AH V EY T'],
    'repair': ['R IH P EH R'],
    'repeat': ['R IH P IY T'],
    'replace': ['R IY P L EY S'],
    'reply': ['R IH P L AY'],
    'report': ['R IY P AO R T'],
    'represent': ['R EH P R IH Z EH N T'],
    'reproduce': ['R IY PR AH D UW S'],
    'request': ['R IH K W EH S T'],
    'require': ['R IH K W AY ER'],
    'rescue': ['R EH S K Y UW'],
    'research': ['R IY S ER CH'],
    'resemble': ['R IY Z EH M B AH L'],
    'resentment': ['R IY Z EH N TM AH N T'],
    'reserve': ['R IH Z ER V'],
    'reside': ['R IH Z AY D'],
    'resign': ['R IH Z AY N'],
    'resist': ['R IH Z IH S T'],
    'resolve': ['R IH Z AA L V'],
    'resort': ['R IY Z AO R T'],
    'resource': ['R IY S AO R S'],
    'respect': ['R IY S P EH K T'],
    'respond': ['R IH S P AA N D'],
    'restore': ['R IH S T AO R'],
    'restrain': ['R IY S T R EY N'],
    'restrict': ['R IH S T R IH K T'],
    'retain': ['R IH T EY N'],
    'retire': ['R IH T AY ER'],
    'retreat': ['R IH T R IY T'],
    'retrieve': ['R IY T R IY V'],
    'reunion': ['R IY Y UW N Y AH N'],
    'reveal': ['R IH V IY L'],
    'revenge': ['R IH V EH N JH'],
    'reverse': ['R IH V ER S'],
    'review': ['R IY V Y UW'],
    'revise': ['R IH V AY Z'],
    'revolution': ['R EH V AH L UW SH AH N'],
    'reward': ['R IY W ER D'],
    'rigid': ['R IH JH IH D'],
    'risk': ['R IH S K'],
    'romantic': ['R OW M AE N T IH K'],
    'routine': ['R UW T IY N'],
    'rudimentary': ['R UW D AH M EH N T EH R IY'],
    'rural': ['R UH R AH L'],
    'sacrifice': ['S AE K R AH F AY S'],
    'safety': ['S EY F T IY'],
    'salmon': ['S AE M AH N'],
    'sanction': ['S AE NG K SH AH N'],
    'satellite': ['S AE T AH L AY T'],
    'satisfaction': ['S AE T IH S F AE K SH AH N'],
    'scale': ['S K EY L'],
    'scenario': ['S AH N EH R IY OW'],
    'schedule': ['S K EH JH UW L'],
    'scheme': ['S K IY M'],
    'scholar': ['S K AA L ER'],
    'science': ['S AY AH N S'],
    'scope': ['S K OW P'],
    'scorn': ['S K AO R N'],
    'script': ['S K R IH P T'],
    'scrutiny': ['S K R UW T AH N IY'],
    'sculpture': ['S K AH L P CH ER'],
    'secrecy': ['S IY K R AH S IY'],
    'secure': ['S IH K Y UH R'],
    'seeker': ['S IY K ER'],
    'segment': ['S EH G M AH N T'],
    'seize': ['S IY Z'],
    'seldom': ['S EH L D AH M'],
    'select': ['S IH L EH K T'],
    'semester': ['S IH M EH S T ER'],
    'senate': ['S EH N AH T'],
    'sensation': ['S EH N S EY SH AH N'],
    'sense': ['S EH N S'],
    'sensitive': ['S EH N S IH T IH V'],
    'sentence': ['S EH N T AH N S'],
    'separate': ['S EH P ER EY T'],
    'sequence': ['S IY KW AH N S'],
    'series': ['S IH R IY Z'],
    'serious': ['S IH R IY AH S'],
    'session': ['S EH SH AH N'],
    'severe': ['S IH V IH R'],
    'shelter': ['SH EH L T ER'],
    'sheriff': ['SH EH R AH F'],
    'shrink': ['SH R IH NG K'],
    'significant': ['S IH G N IH F IH K AH N T'],
    'simulate': ['S IH M Y AH L EY T'],
    'simplify': ['S IH M P L AH F AY'],
    'sinister': ['S IH N IH S T ER'],
    'skeleton': ['S K EH L AH T AH N'],
    'skeptical': ['S K EH P T IH K AH L'],
    'sketch': ['S K EH CH'],
    'slender': ['S L EH N D ER'],
    'slippery': ['S L IH P ER IY'],
    'slope': ['S L OW P'],
    'slogan': ['S L OW G AH N'],
    'so-called': ['S OW K AO L D'],
    'solar': ['S OW L ER'],
    'solemn': ['S AH L AH M N'],
    'sophisticated': ['S AH F IH S T AH K EY T AH D'],
    'source': ['S AO R S'],
    'specialist': ['S P EH SH AH L IH S T'],
    'specify': ['S P EH S AH F AY'],
    'spectrum': ['S P EH K TR AH M'],
    'speculate': ['S P EH K Y AH L EY T'],
    'sphere': ['S F IH R'],
    'spokesman': ['S P OW K S M AH N'],
    'sponsor': ['S P AA N S ER'],
    'spontaneous': ['S P AA N T EY N IY AH S'],
    'spouse': ['S P AW S'],
    'stability': ['S T AH B IH L IH T IY'],
    'stakeholder': ['S T EY K HH OW L D ER'],
    'stance': ['S T AE N S'],
    'standard': ['S T AE N D ER D'],
    'staple': ['S T EY P AH L'],
    'startle': ['S T AA R T AH L'],
    'status': ['S T AE T AH S'],
    'stereotype': ['S T EH R IY AH T AY P'],
    'stimulate': ['S T IH M Y AH L EY T'],
    'stipulate': ['S T IH P Y AH L EY T'],
    'strategic': ['S T R AH T IH JH IH K'],
    'strategy': ['S T R AE T AH JH IY'],
    'streamline': ['S T R IY M L AY N'],
    'strength': ['S T R EH NG K TH'],
    'stress': ['S T R EH S'],
    'strict': ['S T R IH K T'],
    'strive': ['S T R AY V'],
    'structure': ['S T R AH K CH ER'],
    'stubborn': ['S T AH B ER N'],
    'subjective': ['S AH B J EH K T IH V'],
    'subordinate': ['S AH B AO R D AH N EY T'],
    'subscribe': ['S AH B S K R AY B'],
    'subsequent': ['S AH B S IY K W AH N T'],
    'subsidy': ['S AH B S AH D IY'],
    'substance': ['S AH B S T AH N S'],
    'subtle': ['S AH T AH L'],
    'successive': ['S AH K S EH S IH V'],
    'suffice': ['S AH F AY S'],
    'sufficient': ['S AH F IH SH AH N T'],
    'suggestion': ['S AH JH EH S CH AH N'],
    'suitable': ['S UW T AH B AH L'],
    'summit': ['S AH M IH T'],
    'superior': ['S UW P IY R IY ER'],
    'supplement': ['S AH P L AH M AH N T'],
    'suppose': ['S AH P OW Z'],
    'suppress': ['S AH P R EH S'],
    'surplus': ['S ER P L AH S'],
    'surveillance': ['S ER V EY L AH N S'],
    'susceptible': ['S AH S EH P T AH B AH L'],
    'suspicion': ['S AH S P IH SH AH N'],
    'sustain': ['S AH S T EY N'],
    'symbolic': ['S IH M B AA L IH K'],
    'symptom': ['S IH M P T AH M'],
    'syndrome': ['S IH N D R OW M'],
    'systematic': ['S IH S T AH M AE T IH K'],
    'taboo': ['T AH B UW'],
    'tackle': ['T AE K AH L'],
    'tactics': ['T AE K T IH K S'],
    'tailor': ['T EY L ER'],
    'tangible': ['T AE NG G AH B AH L'],
    'target': ['T AA R G IH T'],
    'task': ['T AE S K'],
    'taxation': ['T AE K S EY SH AH N'],
    'telescope': ['T EH L AH S K OW P'],
    'temperament': ['T EH M P ER AH M AH N T'],
    'temporary': ['T EH M P ER EH R IY'],
    'tendency': ['T EH N D AH N S IY'],
    'tension': ['T EH N SH AH N'],
    'terminate': ['T ER M AH N EY T'],
    'territory': ['T EH R AH T AO R IY'],
    'testify': ['T EH S T AH F AY'],
    'textile': ['T EH K S T AY L'],
    'theatrical': ['TH IY AE T R IH K AH L'],
    'theft': ['TH EH F T'],
    'theme': ['TH IY M'],
    'theology': ['TH IY AA L AH JH IY'],
    'theory': ['TH IH R IY'],
    'therapy': ['TH EH R AH P IY'],
    'thereby': ['DH EH R B AY'],
    'thermal': ['TH ER M AH L'],
    'thesis': ['TH IY S IH S'],
    'thorough': ['TH ER OW'],
    'threaten': ['TH R EH T AH N'],
    'threshold': ['TH R EH SH HH OW L D'],
    'throne': ['TH R OW N'],
    'throughout': ['TH R UW AW T'],
    'thrust': ['TH R AH S T'],
    'tolerate': ['T AA L ER EY T'],
    'torture': ['T AO R CH ER'],
    'totalitarian': ['T OW T AH L AH T EH R IY AH N'],
    'totally': ['T OW T AH L IY'],
    'tourism': ['T UH R IH Z AH M'],
    'tract': ['T R AE K T'],
    'tradition': ['T R AH D IH SH AH N'],
    'traffic': ['T R AE F IH K'],
    'tragedy': ['T R AE JH IH D IY'],
    'trail': ['T R EY L'],
    'train': ['T R EY N'],
    'trait': ['T R EY T'],
    'transaction': ['T R AE N Z AE K SH AH N'],
    'transfer': ['T R AE N S F ER'],
    'transform': ['T R AE N S F AO R M'],
    'transit': ['T R AE N Z IH T'],
    'transmit': ['T R AE N Z M IH T'],
    'transparent': ['T R AE N S P EH R AH N T'],
    'transport': ['T R AE N S P AO R T'],
    'treasure': ['T R EH ZH ER'],
    'tremendous': ['T R AH M EH N D AH S'],
    'trend': ['T R EH N D'],
    'tribute': ['T R IH B Y UW T'],
    'trigger': ['T R IH G ER'],
    'trivial': ['T R IH V IY AH L'],
    'tropical': ['T R AA P IH K AH L'],
    'trouble': ['T R AH B AH L'],
    'trumpet': ['T R AH M P AH T'],
    'turbulence': ['T ER BY AH L AH N S'],
    'twilight': ['T W AY L AY T'],
    'tyranny': ['T IH R AH N IY'],
    'ultimate': ['AH L T AH M AH T'],
    'ultraviolet': ['AH L T R OW V AY AH L IH T'],
    'unanimous': ['AH N AE N AH M AH S'],
    'unbearable': ['AH N B EH R AH B AH L'],
    'uncertainty': ['AH N S ER T AH N T IY'],
    'unchanged': ['AH N CH EY N JH D'],
    'unconscious': ['AH N K AA N SH AH S'],
    'undeniable': ['AH N D IH N AY AH B AH L'],
    'undergo': ['AH N D ER G OW'],
    'undermine': ['AH N D ER M AY N'],
    'understand': ['AH N D ER S T AE N D'],
    'undertake': ['AH N D ER T EY K'],
    'undoubtedly': ['AH N D AW T AH D L IY'],
    'uneasy': ['AH N IY Z IY'],
    'unemployment': ['AH N IH M P LOY M AH N T'],
    'unexpected': ['AH N IH K S EH P EH T IH D'],
    'unfair': ['AH N F EH R'],
    'unfortunate': ['AH N F AO R CH AH N AH T'],
    'uniform': ['Y UW N AH F AO R M'],
    'unique': ['Y UW N IY K'],
    'universal': ['Y UW N AH V ER S AH L'],
    'universe': ['Y UW N AH V ER S'],
    'unjust': ['AH N JH AH S T'],
    'unknown': ['AH N N OW N'],
    'unprecedented': ['AH N P R EH S AH D EH N T IH D'],
    'unstable': ['AH N S T EY B AH L'],
    'untangle': ['AH N T AE NG G AH L'],
    'unusual': ['AH N Y UW ZH UW AH L'],
    'uphold': ['AH P HH OW L D'],
    'upset': ['AH P S EH T'],
    'urban': ['ER B AH N'],
    'urge': ['ER JH'],
    'urgent': ['ER JH AH N T'],
    'usage': ['Y UW S IH JH'],
    'utilize': ['Y UW T IH L AY Z'],
    'utter': ['AH T ER'],
    'vacuum': ['V AE K Y UW AH M'],
    'validity': ['V AH L IH D AH T IY'],
    'vanish': ['V AE N IH SH'],
    'variable': ['V EH R IY AH B AH L'],
    'variation': ['V EH R IY EY SH AH N'],
    'various': ['V EH R IY AH S'],
    'vegetarian': ['V EH JH AH T EH R IY AH N'],
    'vehicle': ['V IY AH K AH L'],
    'velocity': ['V AH L AA S AH T IY'],
    'venture': ['V EH N CH ER'],
    'verdict': ['V ER D IH K T'],
    'verify': ['V EH R AH F AY'],
    'version': ['V ER ZH AH N'],
    'vertical': ['V ER T AH K AH L'],
    'vessel': ['V EH S AH L'],
    'veteran': ['V EH T ER AH N'],
    'vibrate': ['V AY B R EY T'],
    'vicinity': ['V AH S IH N AH T IY'],
    'viewpoint': ['V Y UW P OY N T'],
    'vigorous': ['V IH G ER AH S'],
    'village': ['V IH L AH JH'],
    'violate': ['V AY AH L EY T'],
    'virtue': ['V ER CH UW'],
    'visible': ['V IH Z AH B AH L'],
    'vision': ['V IH ZH AH N'],
    'visual': ['V IH ZH AH L'],
    'vital': ['V AY T AH L'],
    'vivid': ['V IH V IH D'],
    'vocabulary': ['V OW K AE B Y AH L EH R IY'],
    'volcano': ['V AA L K EY N OW'],
    'volume': ['V AA L Y UW M'],
    'voluntary': ['V AA L AH N T EH R IY'],
    'vulnerable': ['V AH L N ER AH B AH L'],
    'wage': ['W EY JH'],
    'warehouse': ['W EH R HH AW S'],
    'warfare': ['W AO R F EH R'],
    'warranty': ['W AO R AH N T IY'],
    'warrior': ['W AO R IY ER'],
    'waste': ['W EY S T'],
    'waterfall': ['W AO T ER F AO L'],
    'weaken': ['W IY K AH N'],
    'wealthy': ['W EH L TH IY'],
    'weapon': ['W EH P AH N'],
    'weary': ['W IH R IY'],
    'weave': ['W IY V'],
    'webpage': ['W EH B P EY JH'],
    'wedding': ['W EH D IH NG'],
    'welfare': ['W EH L F EH R'],
    'western': ['W EH S T ER N'],
    'wheat': ['W IY T'],
    'wheel': ['W IY L'],
    'whip': ['W IH P'],
    'whisper': ['W IH S P ER'],
    'widespread': ['W AY D S P R EH D'],
    'widow': ['W IH D OW'],
    'willingness': ['W IH L IH NG N AH S'],
    'windy': ['W IH N D IY'],
    'wisdom': ['W IH Z D AH M'],
    'withdraw': ['W IH DH D R AO'],
    'withstand': ['W IH DH S T AE N D'],
    'witness': ['W IH T N AH S'],
    'wonderful': ['W AH N D ER F AH L'],
    'workshop': ['W ER K SH AA P'],
    'worldwide': ['W ER L D W AY D'],
    'worship': ['W ER SH IH P'],
    'worthwhile': ['W ER TH W AY L'],
    'wrinkle': ['R IH NG K AH L'],
    'wrist': ['R IH S T'],
    'xenophobia': ['Z EH N AH F OW B IY AH'],
    'yearn': ['Y ER N'],
    'yield': ['Y IY L D'],
    'youthful': ['Y UW TH F AH L'],
    'zeal': ['Z IY L'],
    'zenith': ['Z IY N IH TH'],
    'zest': ['Z EH S T'],
    'zoology': ['Z OW AA L AH JH IY']
}

welcome = "Hii, I am your assistant what can I do For You"
print(welcome)
speak(welcome)


while True:
    user_input = takeCommand().lower()

    if user_input == 'exit':
        speak("Goodbye!")
        break
    elif 'wikipedia' in user_input:  #if wikipedia found in the query then this block will be executed
            speak('Searching Wikipedia...')
            user_input = user_input.replace("wikipedia", "")
            results = wikipedia.summary(user_input, sentences=2) 
            speak("According to Wikipedia")
            print(results)
            speak(results)
    elif 'open youtube' in user_input or 'search youtube' in user_input:
        if user_input == 'open youtube':
            webbrowser.open('https://www.youtube.com/')
        else:
            user_input = user_input.replace("search youtube", "")
            words = user_input.split()
            search = 'https://www.youtube.com/results?search_query='
            for word in words:
                search += (str(word)) + '+'
            webbrowser.open(search)
    elif 'open google' in user_input or 'search google' in user_input:
        if user_input == 'open google':
            webbrowser.open('chrome://newtab/')
        else:
            user_input = user_input.replace("search google", "")
            words = user_input.split()
            search = 'https://www.google.com/search?q='
            for word in words:
                search += (str(word)) + '+'
            webbrowser.open(search)
    elif 'pronounce' in user_input:
        user_input = user_input.replace("pronounce", "")
        words = user_input.split()
        speak(user_input)
        # for word in words:
        #     if word in correct_words_phonetic:
        #         speak(f"Correctly recognized: {word}")
        #     else:
        #         suggested_correction = correct_word(word, correct_words_phonetic)
        #         if suggested_correction:
        #             speak(f"Did you mean {suggested_correction}?")
        #         else:
        #             speak(f"Sorry, I couldn't recognize the word: {word}")